# GNU Autotool

## Genel Bakış

* Autotools
	+ =>> Autoconf, automake ve libtool için GNU Yapı Sistemi veya umbrela adı. GNU otomatik araçları birçok açık kaynaklı Linux projesi ve gömülü Linux tarafından kullanılmaktadır.

* GNU Autotools Kullanan Bazı Projeler:
	+ [GNU Emacs](https://github.com/emacs-mirror/emacs)
	+ [GNU Glibc](https://github.com/bminor/glibc) (Linux'ta kullanılan GNU C Çalışma Zamanı Kütüphanesi)
	+ [GNU GCC Compiler](https://github.com/gcc-mirror/gcc/blob/master/configure.ac)
	+ [NetworkManager](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/blob/master/configure.ac) (Linux ağ yöneticisi arka plan programı)
	+ [Htop tool](https://github.com/hishamhm/htop/blob/master/configure.ac) - htop etkileşimli bir metin modu süreç görüntüleyicisidir.
	+ [Nhttp2](https://github.com/nghttp2/nghttp2/blob/master/configure.ac) - (Köprü Metni Aktarım Protokolü sürüm 2'nin C'de uygulanması.)
	+ [LibFFI](https://github.com/mingw-deb/libffi/blob/master/configure)
	+ [LibSodium](https://github.com/wireapp/libsodium/blob/master/configure.ac)

* Çoğunlukla Unix benzeri veya POSIX benzeri işletim sistemlerinde, özellikle Linux'ta kullanılır.

* Motivasyon:
	+ Eski sistemler veya yazılımlarla başa çıkmak,
	+ Alternatif inşa sistemleri hakkında bilgi edinin,
	+ Mevcut açık kaynaklı projelerin bakımı,
	+ GNU otomatik araçlarını CMake'e taşıma olanağı,
	+ Gömülü Linux.

* Desteklenen IDE'ler (Entegre Geliştirme Ortamları)
	+ Eclipse IDE
		- [Linux Araçları Eklentisi](https://www.eclipse.org/linuxtools/)
		- [Eclipse CDT Autotools Kullanım Kılavuzu](https://wiki.eclipse.org/CDT/Autotools/User_Guide)
	+ NetBeans
		- [CppGnuAutoTools Eklentisi](http://plugins.netbeans.org/plugin/51647/cppgnuautotools)
	+ QTCreator
		- [Autotools Proje Yöneticisi Eklentisi](https://doc.qt.io/qtcreator/creator-projects-autotools.html)

* Şunun için kullanılabilir:
	+ Linux, MacOSX, FreeBSD, OpenBSD, NetBSD vb.

* Belgeler:
	+ [GNU Autoconf](https://www.gnu.org/software/autoconf/)
	+ [GNU Automake](https://www.gnu.org/software/automake/automake.html)
	+ [GNU Libtool](https://www.gnu.org/software/libtool/libtool.html)

* Desteklenen Programlama Dilleri
	+ C
	+ C++
	+ Objective C
	+ Fortran
	+ Fortran77
	+ Erlang

* Terminal Belgeleri:
	+ `₺ info automake`
	+ `₺ info autoconf`
	+ `₺ info libtool`

* Ortak yapı yapılandırma olanakları
	+ `₺ ./configure`
	+ `₺ make`
	+ `₺ make install => Install application.`
	+ `₺ … … ..`

## Referans Kartı

### Kurulum

##### Fedora Linux Dağıtımına Kurulumu:

`₺ sudo dnf install autoconf automake`

##### Ubuntu veya Debian Linux Dağıtımlarına Kurulumu:

`₺ sudo apt-get install autoconf automake`

### GNU Autotools için GNU Make Komutları

```bash
Make Komutları -> Açıklamaları
₺ make -> Uygulamayı oluştur
₺ make -j4 -> 4 iş parçacığı kullanarak uygulama oluşturma

 	 
₺ make check -> Testleri çalıştırın
 	 
₺ make clean -> Derleme dosyalarını temizle
₺ make distclean -> Oluşturulan otomatik dosyaları kaldırın.
 	 
₺ make install -> / Usr / loca / bin, / etc,… için uygulamayı sisteme yükleyin.
₺ make intallcheck -> Kurulumu kontrol edin
₺ make uninstall -> Yükleme dosyalarını kaldırma
 	 
₺ make dist -> Kaynak dağıtım tarball oluştur
₺ make distcheck -> Dist yapmaya benzer, ancak derleme olup olmadığını kontrol eder, bir tarball oluşturur.
```

#### Çoğu Yapılandırma değişkeni

```bash
Değişken -> Açıklama
CC -> C derleyici	 
CXX -> C++ derleyici	 
 	 	 
CPPFLAGS -> C ve C ++ Önişlemci bayrakları	 
CFLAGS -> C derleyicisinin bayrakları
CXXFLAGS -> C ++ derleyicisinin bayrakları 
 	 	 
LDFLAGS -> Bağlayıcı Bayrakları 
LIBS -> Bağlayıcıya aktarılan kütüphaneler
```

##### Faydalı ./configure (Autotools) komut satırı anahtarları

Bunlar, açık kaynaklı uygulamalar veya kütüphaneden kaynaktan kütüphaneler oluşturmak için kullanışlı ve yinelenen komut satırı anahtarlarıdır.

* ./Configure yardım kısmını göster

`₺ ./configure --help`

* Genel ./configure kullanım örneği.

```bash
# ---- Example 1 --------------------#
# Install to /usr, /usr/bin, /usr/include, /usr/lib, /usr/lib64 on Linux 
₺ ./configure  
₺ make 
₺ make install 

# ---- Example 2 --------------------#
₺ ./configure  --with-feature1 --without-feature2 --eanable-option1 --enable-option2=no 
₺ make 
₺ make install 

# ---- Example 3 --------------------#
# Install to custom location (directory)
₺ ./configure --prefix=/my/custom/location  --with-feature1 \
     --without-feature2 --eanable-option1 --enable-option2=no --disable-option3

₺ make -j4 # Build using 4 threads (faster)
₺ make install 
```

### Kullanıcılar için Autotools iş akışı

ADIM 1: Kullanıcı ./configure inşa seçeneğini seçerek çalıştırır;

```bash
# Install application in default directory
₺ ./configure

# Install the application in another directory 
₺ ./configure --prefix=/home/user/juliuscaesar/opt
```

ADIM 2: İnşa için (GNU) make çalıştırmak.

```bash
₺ make 

# Run GNY make with 4 threads 
₺ make -j4 

# Run ₺ make and ₺ make install in a single step 
₺ make -j4 && sudo make install 
```

ADIM 3: Kurulum.

```bash
₺ make install 

# If permission is needed 
₺ sudo make install 
```

### Geliştirici Worflow

ADIM 1:

* => Dosya oluştur:
	+ autoconf için configure.ac - M4 makro işlemcisi tarafından işlenen Bash'a (Bourne Kabuk Betiği) benzer bir dilde yazılmıştır.
		- Not: Makro invokasyonlardaki boşluklara dikkat etmek gerekir.
	+ Automake için Makefile.am.

ADIM 2:

* => Geliştirici ./configure ve Makefile.in dosyalarını oluşturan autoreconf komutunu çalıştırır.

ADIM 3:

* => Oluşturulan dosyaları çalıştırarak test edin:
	+ `₺ ./configure && make && make install.`

## Örnek: Temel GNU autotools projesi

### Proje Dosyaları

Dosya: main.cpp

```Cpp
#include <iostream>

int main()
{
  std::cout << "Hello world autotools" << std::endl;
  return 0;
}
```

##### Dosya: configure.ac

```bash
#------- File: configure.ac ----------#
#-------------------------------------# 

# app => Is the file name without extensions
# 0.1 => Is the version 
AC_INIT( [app], [0.1], [maintener@email.com])

# Require at least autoconf version >= 2.68 
AC_PREREQ([2.68])  
AM_INIT_AUTOMAKE([-Wall -Wextra])

# ./configure creates a Makefile
AC_CONFIG_FILES([Makefile])

# Find and check C compiler 
AC_PROG_CC
# Find and check a C++ compiler 
AC_PROG_CXX 
AC_OUTPUT 
```

##### Dosya: Makefile.am

```bash
# Contains all executable targets 
bin_PROGRAMS = app

# Sources for the executable targets 
app_SOURCES  = app.cpp 
```

##### Dosya: clean.sh

* Geçerli dizini temizlemek için kullanılan yardımcı bash betiği.

```bash
#!/usr/bin/env sh 
rm -v configure config.log config.status install-sh missing aclocal.m4 compile depcomp 
rm -vrf autom4te.cache
rm -v *.o *.bin *.so
rm *~ # Remove temporary files 
```

### İnşa Adımları

ADIM 1: Geliştirici tarafından gerçekleştirilen kısım

* GNU autotools araçlarının gerektirdiği ek meta veri dosyaları oluşturun

`₺ touch README NEWS AUTHORS ChangeLog # Set metadata files`

ADIM 2: Geliştirici tarafından gerçekleştirilen kısım

* ./Configure kabuk komut dosyası ve ek dosyaları oluşturmak için atuoreconf komutunu çalıştırın.
* Çalıştır: `₺ autoreconf -i -v`

```bash
₺ autoreconf -i -v 

autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --no-force
configure.ac:11: warning: unknown warning category 'extra'
configure.ac:17: installing './compile'
configure.ac:11: installing './install-sh'
configure.ac:11: installing './missing'
Makefile.am: installing './depcomp'
autoreconf: Leaving directory `.'
```

ADIM 3: Kullanıcı tarafından gerçekleştirilen kısım

* Aşağıdaki adımlar, uygulamayı sisteme veya yerel bir dizine yüklemek için son kullanıcılar veya bakımcılar tarafından gerçekleştirilir.
* Yapılandırma komut dosyasını çalıştırarak Makefile dosyasını oluşturun.

Çalıştır: `₺ ./configure`

```bash
₺ ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk

... ... ...   ... ... ...   ... ... ...   ... ... ... 
     # Suppress output for breviety purposes 
... ... ...   ... ... ...   ... ... ...   ... ... ... 

checking dependency style of g++... gcc3
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: executing depfiles commands
```

Çalıştır: Clang kullanmak için `₺ ./configure CC=clang CXX=clang++`

`₺ ./configure CC=clang CXX=clang++`

ADIM 4: Kullanıcı tarafından gerçekleştirilen kısım

* Makefile'ı çalıştırın (GNU make)

Çalıştır: `₺ make`

```bash
₺ make

g++ -DPACKAGE_NAME=\"app\" -DPACKAGE_TARNAME=\"app\" -DPACKAGE_VERSION=\"0.1\"  \
    -DPACKAGE_STRING=\"app\ 0.1\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\"   \
     -DPACKAGE=\"app\" -DVERSION=\"0.1\" -I.     -g -O2 -MT app.o -MD -MP -MF   \
    .deps/app.Tpo -c -o app.o app.cpp \
    mv -f .deps/app.Tpo .deps/app.Po \

 g++  -g -O2   -o app app.o  
```

Çalıştır: `₺ make install`

```bash
₺ make install
make[1]: Entering directory '/home/archbox/projects/autools1'
 /usr/bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c app '/usr/local/bin'
/usr/bin/install: cannot create regular file '/usr/local/bin/app': Permission denied
make[1]: *** [Makefile:313: install-binPROGRAMS] Error 1
make[1]: Leaving directory '/home/archbox/projects/autools1'
make: *** [Makefile:615: install-am] Error 2
```

Çalıştır: `₺ make dist` => Bir tarball dağılımı oluşturun.

```bash
₺ make dist
make  dist-gzip am__post_remove_distdir='@:'
make[1]: Entering directory '/home/archbox/projects/autools1'
if test -d "app-0.1"; then find "app-0.1" -type d ! -perm -200 -exec chmod u+w {} ... ... 
test -d "app-0.1" || mkdir "app-0.1"

  .. ... ... ... ... ... ... 
rm -rf "app-0.1" || { sleep 5 && rm -rf "app-0.1"; }; else :; fi
```

Tarball dosyasını kontrol edin:

```bash
    ₺ tar -tzvf app-0.1.tar.gz 
drwxrwxr-x 1000/1000         0 2019-10-21 15:23 app-0.1/
-rw-rw-r-- 1000/1000     42147 2019-10-21 15:22 app-0.1/aclocal.m4
-rwxrwxr-x 1000/1000    154043 2019-10-21 15:22 app-0.1/configure
-rw-rw-r-- 1000/1000       546 2019-10-21 15:01 app-0.1/configure.ac
-rw-rw-r-- 1000/1000       101 2019-10-21 14:28 app-0.1/app.cpp
-rwxr-xr-x 1000/1000     14676 2019-10-21 15:22 app-0.1/install-sh
-rw-rw-r-- 1000/1000         0 2019-10-21 15:02 app-0.1/ChangeLog
-rwxr-xr-x 1000/1000      6872 2019-10-21 15:22 app-0.1/missing
-rwxr-xr-x 1000/1000     23566 2019-10-21 15:22 app-0.1/depcomp
-rw-rw-r-- 1000/1000         0 2019-10-21 15:02 app-0.1/AUTHORS
-rw-r--r-- 1000/1000     35147 2019-10-21 15:01 app-0.1/COPYING
-rw-r--r-- 1000/1000     15756 2019-10-21 15:01 app-0.1/INSTALL
-rwxr-xr-x 1000/1000      7381 2019-10-21 15:22 app-0.1/compile
-rw-rw-r-- 1000/1000       117 2019-10-21 14:52 app-0.1/Makefile.am
-rw-rw-r-- 1000/1000         0 2019-10-21 15:02 app-0.1/README
-rw-rw-r-- 1000/1000         0 2019-10-21 15:02 app-0.1/NEWS
-rw-rw-r-- 1000/1000     23477 2019-10-21 15:22 app-0.1/Makefile.in
```

ADIM 5:

* Uygulamayı test edin.

```bash
# Check executable file 
₺ file app
app: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter 
/lib64/l, for GNU/Linux 3.2.0, BuildID[sha1]=29f5b104ac648c3286ed616ea4cf4007a6b51ae2, 
with debug_info, not stripped

# Run native executable 
₺ ./app
Hello world autotools
```

#### Uygulamayı yeni bir konuma oluşturun ve yükleyin

Configure betiğini çalıştırın.

```bash
# Build with clang and install at ~/opt/app-test 
₺ ./configure CC=clang CXX=clang++ --prefix=₺HOME/opt/app-test
```

Make ve make install komutlarını çalıştırın

```bash
₺ make install
make[1]: Entering directory '/home/archbox/projects/autools1'
 /usr/bin/mkdir -p '/home/archbox/opt/app-test/bin'
  /usr/bin/install -c app '/home/archbox/opt/app-test/bin'
make[1]: Nothing to be done for 'install-data-am'.
make[1]: Leaving directory '/home/archbox/projects/autools1'
```

Test kurulumu:

```bash
₺ tree /home/archbox/opt/app-test
/home/archbox/opt/app-test
└── bin
    └── app

1 directory, 1 file
```

Uygulamayı çalıştırın:

```bash
₺ /home/archbox/opt/app-test/bin/app 
Hello world autotools
```

## İleri düzey tavsiye kaynaklar

+ [Autotools Nasıl Kullanılır](https://eklitzke.org/how-to-autotools)
+ [GNU Autotools Kitabı](https://www.star.bnl.gov/~liuzx/autobook.html)
+ [Gömülü Linux Konferansı 2016 - GNU Autotools Eğitimi](https://elinux.org/images/4/43/Petazzoni.pdf)
+ [Bölüm 1: GNU Otomobillerine Kısa Bir Giriş](http://freesoftwaremagazine.com/articles/brief_introduction_to_gnu_autotools/)
+ [Nasıl yapılandırma betiği oluştururum?](https://stackoverflow.com/questions/10999549/how-do-i-create-a-configure-script)
+ [Autotools — Fedora Geliştirici Portalı](https://developer.fedoraproject.org/tech/languages/c/autotools.html)
+ [GNU Derleme Sistemi (A.K.A. GNU Autotools) ile Üretilen C / C ++ Projesi: NetBeans vs. Eclipse CDT](http://thegreyblog.blogspot.com/2013/09/cc-project-built-with-gnu-build-system.html)

